minecraft_version=26.1.2
java_version=25
mod_version=0.1.3
rinlib_version=1.0.0
mod_id=keep_my_sword
mod_name=Keep My Sword
mod_authors=RinChan
mod_license=GPL-3.0-or-later
mod_description=Keeps broken damageable items as repairable model-only items.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
