plugins {
    alias libs.plugins.modDevGradle
    id 'java-library'
}
neoForge { neoFormVersion = libs.versions.neoForm }
sourceSets.main.java.srcDir '../../common/src/main/java'
sourceSets.main.resources.srcDir '../../common/src/main/resources'
dependencies {
    implementation files("${providers.gradleProperty('rinlibDir').get()}/rinlib-${rinlib_version}+${minecraft_version}-neoforge.jar")
}
configurations {
    commonJava { canBeConsumed = true }
    commonResources { canBeConsumed = true }
}
artifacts {
    sourceSets.main.java.srcDirs.each { commonJava it }
    commonResources file('../../common/src/main/resources')
}
tasks.withType(JavaCompile).configureEach { options.release = java_version as int; options.encoding = 'UTF-8' }
java { toolchain.languageVersion = JavaLanguageVersion.of(java_version as int) }
