minecraft_version=26.2
java_version=25
fabric_loader_version=0.19.3
fabric_api_version=0.158.0+26.2
mod_version=1.0.0
rinlib_version=1.0.0
mod_id=keep_my_sword
mod_name=Keep My Sword
mod_authors=RinChan
mod_license=GPL-3.0-or-later
mod_description=Keeps broken damageable items as repairable model-only items.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
